management:
  security:  
   enabled: false      
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
    
server:
    port: 4005
    
spring:  
  application:
    name: search
    
  data:
    mongodb:                 
      uri: mongodb://BingoBongo:Abcdf@mongodb:27017/searchDB?ssl=false&connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=100&maxIdleTimeMS=900000&authSource=admin

            
eureka:
  instance:  
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    leaseExpirationDurationInSeconds: 3
  client:
    enabled: true
    registryFetchIntervalSeconds: 5   
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}